### ISSUE TITLE
LibArtifactData-1.0 library and others are missing from the WowAce package

### ISSUE THREAD

**Issue by Tonyleila** [AdiAddons/AdiButtonAuras#223] opened 2016-08-14 01:33 UTC
I have set up curse to install the nolib versions but this is the only addon where its not working because the libs are not on curse or in the addon folder.

I get this errors: http://www.wowinterface.com/forums/showthread.php?t=54049

**Comment by Rainrider** [comment] 2016-08-14 11:32
I think the problem is that I need to push a release so that the project syndicates with curse. Apparently the beta tag was not enough.

I just pushed a release tag and LAD is now queued for approval. After that I should work as intended I think. Please tell me if not so.

**Comment by Rainrider** [comment] 2016-08-14 22:59
Should be fixed once b5c63baca3a17dab0ba8da354ca6095d250d9bd8 has been processed by the [wowace packager](https://www.wowace.com/packager/).

**Closed by Rainrider** 2016-08-14 22:59 UTC
