### ISSUE TITLE
Earth Shield Macro Stacks/CD Sometimes Not Visible

### ISSUE THREAD

**Issue by Oldthrush** [AdiAddons/AdiButtonAuras#297] opened 2018-08-02 19:37 UTC
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
2.0.18

#### How did you install the addon (twitch client/manually)?
Twitch Client

#### If using the twitch client, what type of release did you install (alpha/beta/release)?
Release

#### If you installed manually, where did you download the addon from?
N/A

#### Which type of installation did you choose (nolib/normal)?
N/A

#### If your report is about a missing or wrong spell provide the following information:
  - Your class: Shaman
  - Your spec: Restoration and Enhance
  - Name of the spell (and spell id if known): Earth Shield
  - Source of the spell (core ability/talent/pvp): talent
  - Do you use a macro to cast the spell (post the macro if so): yes
`#showtooltip
/cast [spec:2,talent:3/2,@mouseover,help,nodead][spec:2,talent:3/2][spec:3,talent:2/3,@mouseover,help,nodead][spec:3,talent:2/3]Earth Shield; Astral Shift`

#### If you have an error report, copy it below:
N/A

When using the macro and cast on target (EStarget), the macro icon shows the following behaviors:

1. Maintain EStarget and mouseover harm: cd/stack visible
2. Maintain EStarget and mouseover noharm: cd/stack not visible
3. Drop EStarget, or target other: cd/stack not visible

**Comment by Rainrider** [comment] 2018-08-03 17:38
All 3 are working as intended for what I can tell. According to your macro the unit precedence is as follows:
mouseover,help,nodead -> target -> player

So for the listed cases it works like that:
1. mouseover condition falls through, because harm -> target condition holds -> target has ES -> spell info is shown
2. mouseover condition holds -> mouseover has no ES -> nothing is shown
3. mouseover condition falls through (no mouseover) 
   from here either ... or:
    -> target condition holds -> target has no ES -> nothing is shown
    -> target condition falls through (no target) -> player condition holds -> player has no ES -> nothing is shown

Btw, if you do PvP and you target and unfriendly player with ES, you will get their ES info on your macro button (unless you have a friendly mouseover). This is because you are not specific enough in the spec/talent conditionals. `[spec:2,talent:3/2,help]` should fix this.

**Comment by Rainrider** [comment] 2018-08-03 17:42
Btw there seems to be an issue when you loose your mouseover. Cast ES on yourself, untarget and mouseover a friendly player -> nothing is shown (this is ok). However when you loose your mouseover, the info for ES on yourself should be shown, which is currently not the case. I'll see into that.

**Comment by Rainrider** [comment] 2018-08-03 21:24
Should be fixed with bd4bfe17448b187fe4285be5b622dba39be361f9.

**Closed by Rainrider** 2018-08-03 21:24 UTC
