### ISSUE TITLE
addon diddnt work since legion gets online

### ISSUE THREAD

**Issue by MammonGer** [AdiAddons/AdiButtonAuras#232] opened 2016-09-02 21:58 UTC
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?

AdiButtonAuras 2.0-1-g8dc73e0-Global

#### How did you install the addon (curse client/manually)?

curse client

#### If using the curse client, what type of release did you install (alpha/beta/release)?

alpha but also tryed beta and release

#### Which type of installation did you choose (nolib/normal)?

i think i had no option when i download with curse 

#### If your report is about a missing or wrong spell provide the following information:
  
with any class i testet it the most, nearly all class spells are not green highlightet so i can not chose them

#### If you have an error report, copy it below:

[Error 000000002F0B9530] gefangen, klicke auf den Link für mehr Informationen.
Gildennachricht des Tages: Sicher dir deinen Platz im Raid & trage dich im Forum ein >> derzeit 16 Raider << Gesucht werden noch Range DDs und Heiler
Uníqué ist jetzt offline.
...ras\libs\LibPlayerSpells-1.0\LibPlayerSpells-1.0-8.lua:330: attempt to index field 'CROWD_CTRL' (a nil value)
...ras\libs\LibPlayerSpells-1.0\LibPlayerSpells-1.0-8.lua:330: in function `(for generator)'
Interface\AddOns\AdiButtonAuras\rules\Common.lua:197: in function <Interface\AddOns\AdiButtonAuras\rules\Common.lua:22>
[C]: ?
Interface\AddOns\AdiButtonAuras\core\Core.lua:373: in function <Interface\AddOns\AdiButtonAuras\core\Core.lua:365>
Interface\AddOns\AdiButtonAuras\core\Core.lua:388: in function `?'
...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:147: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:92: in function `Fire'
...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0-19.lua:346: in function <...ttonAuras\libs\LibSpellbook-1.0\LibSpellbook-1.0.lua:308>
(tail call): ?
nil

**Comment by Rainrider** [comment] 2016-09-03 21:17
You are having an old LibPlayerSpells lying around as a separate addon. I'll push a release to make the curse client update this.

**Comment by Rainrider** [comment] 2016-09-03 22:10
Could you please update your addons by using the curse client and tell me if the issue is fixed now?

**Comment by MammonGer** [comment] 2016-09-08 13:29
its fixed now, but sometimes i got still an error message
i post them when i got it the next time

**Comment by Rainrider** [comment] 2016-09-09 07:45
Please check the other issues or open a new one if you have other problems. I'm closing this one because the issue topic is now fixed.

**Closed by Rainrider** 2016-09-09 07:45 UTC
