### ISSUE TITLE
Adibuttons wow client crash with WW Monk

### ISSUE THREAD

**Issue by bizzarojerry** [AdiAddons/AdiButtonAuras#337] opened 2020-05-30 14:55 UTC
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
2.2.0

#### How did you install the addon (twitch client/manually)?
twitch client

#### If using the twitch client, what type of release did you install (alpha/beta/release)?
release

#### Which type of installation did you choose (nolib/normal)?
normal

#### If your report is about a missing or wrong spell provide the following information:
  - Your class:  Monk
  - Your spec: WW
  - Name of the spell (and spell id if known):
  - Source of the spell (core ability/talent/pvp):
  - Do you use a macro to cast the spell (post the macro if so):

#### If you have an error report, copy it below:

I am running ADI buttons on 5 different classes, RET:pally, FROST:DK, Havok:DH, BM:Hunter, WW:Monk.

All works all except for the WW:monk. The crash first appeared in 8.3 (before then it was rock solid) in the Visions and in the new zones of Uldum and Vale. The client will randomly freeze (goes white screen and instantly windows will pop up saying the application has stopped) in those zones and instance.

I disabled the AdiButton mod and the the monk is playable in visions (3 masks) and in the Vale and Uldum zones. 

I am perplexed that only on the WW monk crashes the client when all the other toons have the same addon list, only the monk has a character specific addon list as that is the only character that has AdiButtonAuras disabled to allow me the play the game with that toon. If required I can provide you with toon name to help determine if its a piece of gear or azerite affect that is triggering the crash.

**Comment by Rainrider** [comment] 2020-08-13 20:27
Closing this as it is quite old. Also I don't have an active sub and I can't reproduce it.

**Closed by Rainrider** 2020-08-13 20:27 UTC
