### ISSUE TITLE
Shift+RightClick on artifact weapon does not open artifact tree

### ISSUE THREAD

**Issue by neun0eil** [AdiAddons/AdiButtonAuras#231] opened 2016-09-02 08:39 UTC
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
2.0

#### How did you install the addon (curse client/manually)?
Curse Client

#### If using the curse client, what type of release did you install (alpha/beta/release)?
Release

#### Which type of installation did you choose (nolib/normal)?
Normal

#### If you have an error report, copy it below:
Shift+RightClick on artifact weapon does not open artifact tree after some actions in a game (loading screen mainly), maybe LibArtifactData-1.0 has an issue. /reload does not fix the problem, only reconnecting character. I can reproduce the bug several times by switching dalaran/class hall portals.
Is there a way to disable artifact weapon support until a fix will be available?

**Comment by PhoenixPower** [comment] 2016-09-02 17:37
I think I have the same issue

> Message: Interface\FrameXML\MainMenuBar.lua:126: Usage: GetCostForPointAtRank(rank)
> Time: 09/02/16 19:24:45
> Count: 1
> Stack: Interface\FrameXML\MainMenuBar.lua:126: in function <Interface\FrameXML\MainMenuBar.lua:124>
> ...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:234: in function <...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:229>
> ...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:295: in function <...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:282>
> ...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:313: in function <...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:312>
> 
> Locals: pointsSpent = nil
> artifactXP = nil
> numPoints = 0

Going through the TOC it seems that LibArtifactData is a optional dependency so I just commented out the following line in AdiButtonAuras.toc as a temporary solution

`libs\LibArtifactData-1.0\LibArtifactData-1.0.lua`

**Comment by Rainrider** [comment] 2016-09-02 19:31
See Rainrider/LibArtifactData-1.0#1 I'll be tommorow evening back from my
vacation and will try to fix it on Sunday.

**Comment by Rainrider** [comment] 2016-09-03 22:11
Does the issue still persist?

**Comment by neun0eil** [comment] 2016-09-04 08:59
I have disabled Exorsus Raid Tools and updated LibArtifactData-1.0 to this commit https://github.com/AlexejK/LibArtifactData-1.0/commit/185d2b533ee01049c91d724777099d19f86a6683
No more issue, Thanks for the help.

**Comment by Rainrider** [comment] 2016-09-04 10:11
The "fix" you linked is not a fix. The reported error is caused by the variable `rank` being a nil instead of a number. It should read `total = total + GetCostForPointAtRank(rank or 0)` instead, but I don't think this is a good solution since it won't fix the error but rather mask it and return wrong values.

Exorsus Raid Tools is horribly coded imho and that not only in regard of artifacts handling. The authors even have the following in their code:
```lua
local function BlizzUiFix_DealWithErrors()
	if ArtifactFrame and ArtifactFrame:IsVisible() then
		ArtifactFrame:Hide()
		if ScriptErrorsFrame then
			ScriptErrorsFrame:Hide()
		end
	end
end
```
so it is obvious that they know their code causes errors and they just hide the frames. Naming that function `BlizzUiFix_DealWithErrors` shows a sense of humor though.

If you keep using AlexejK fork, please contact him with your issues from now on. I won't provide support for code that is not part my own project.

**Comment by Rainrider** [comment] 2016-09-04 10:18
Just to clarify, the fork of AlexejK is not related to the problem you have, I just mean that what he tries to fix is not about the issue you have and his approach cannot be applied to your issue for the reasons I stated above.

**Comment by Rainrider** [comment] 2016-09-09 07:59
@PhoenixPower 
> Going through the TOC it seems that LibArtifactData is an optional dependency so I just commented out the following line in AdiButtonAuras.toc as a temporary solution

I missed to comment on that. Don't do this as it will create other problems. LibArtifactData is a required dependency for LibSpellbook. Required libraries are often listed under #OptDeps because of the way they are being shipped. If you have the normal version of ABA, the library is loaded from within the addon itself and in this case you probably don't have it as a standalone addon. Thus, if it was listed as a required dependency in the .toc, ABA won't load because it will not find it, despite having it embedded. In your case your fix didn't do anything, since the lib was loaded from within the addon.

**Comment by Balmorian** [comment] 2016-09-09 20:14
In point of fact adibutton auras has been borked with regard to this since legion launch, the only fix I found was to remove the artifact lib folder from the addon entirely.  It does throw an error regarding spellbook lib at startup but I ignore it and everything seems to work well enough for my needs.  It certainly beats having to relog every single time I want to access my artifact interface and even then praying I can get it open before adibuttons throws the mainbar error.  I will be a very happy camper to see this one fixed properly, and won't be updating my install until it is.

**Comment by Rainrider** [comment] 2016-09-09 22:06
Can you reproduce your issue with only running an updated version of
AdiButtonAura without other add-ons?

**Comment by Rainrider** [comment] 2016-10-05 16:45
Shoud be resolved. Reopen if not.

**Closed by Rainrider** 2016-10-05 16:45 UTC
Labels: duplicate
