### ISSUE TITLE
Problem with a macro 

### ISSUE THREAD

**Issue by FelipeOrtuzarSawred** [AdiAddons/AdiButtonAuras#336] opened 2020-04-24 02:28 UTC
#### How did you install the addon (twitch client/manually)?
manually

#### If you installed manually, where did you download the addon from?
github.com

#### Which type of installation did you choose (nolib/normal)?
normal

#### If your report is about a missing or wrong spell provide the following information:
  - Your class: Priest
  - Your spec: Discippline
  - Name of the spell (and spell id if known): Purge the Wicked
  - Source of the spell (core ability/talent/pvp): core
  - Do you use a macro to cast the spell (post the macro if so): Yes
#showtooltip
/cast [help] Power Word: Shield; Purge the Wicked

#### If you have an error report, copy it below:

Hello, I have had a problem with the addon when I use the sig macro Example:

#showtooltip
/ cast [help] Power Word: Shield; Purge the Wicked

It turns out that it does not work with the Ourge the Wicked skill and if I do it in reverse Example:

#showtooltip
/ cast [harm] Purge the Wicked; Power Word: Shield

Power Word: Shield does not work.

Search the forum for something related but was unsuccessful.

Cheers

**Comment by Rainrider** [comment] 2020-08-13 20:28
Closing this as it is quite old. Also I don't have an active sub and I can't reproduce it.

**Closed by Rainrider** 2020-08-13 20:28 UTC
